import { Container, Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter, Lora, Mansalva } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "./theme-config.css";

// Configure Inter as default font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const mansalva = Mansalva({
  subsets: ["latin"],
  variable: "--font-mansalva",
  weight: ["400"],
  display: "swap",
});

// Configure Fira Sans for headings
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${mansalva.variable} ${lora.variable}`}
    >
      <body className="antialiased ">
        <Theme accentColor="plum" radius="full">
          <Flex className="flex-col bg-[var(--plum-1)] text-[var(--plum-11)] min-h-dvh">
            <Container>
              <NavBar />
              <p>I need to push. again</p>
              <main className="p-4">{children}</main>
            </Container>
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
